// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfkhlftneneemfnutasz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlma2hsZnRuZW5lZW1mbnV0YXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzYyMjYsImV4cCI6MjA1ODExMjIyNn0.5KvcAt26HICUCO1McJ38xPGnUK3KbyUkpvNFw5ezrXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);